/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeBean_Bean */

#ifndef _Included_nativeBean_Bean
#define _Included_nativeBean_Bean
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeBean_Bean
 * Method:    dropMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_dropMemory
  (JNIEnv *, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    allocateMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_allocateMemory
  (JNIEnv *, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    chainMethods
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_chainMethods
  (JNIEnv *, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    stringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nativeBean_Bean_stringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nativeBean_Bean
 * Method:    callObjectMethod
 * Signature: (LnativeBean/Bean;)V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_callObjectMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    changeFieldValue
 * Signature: (LnativeBean/Bean;)V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_changeFieldValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    allocateStructure
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nativeBean_Bean_allocateStructure
  (JNIEnv *, jobject);

/*
 * Class:     nativeBean_Bean
 * Method:    getStructureValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nativeBean_Bean_getStructureValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nativeBean_Bean
 * Method:    freeStructure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nativeBean_Bean_freeStructure
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
