/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLib_CMatrix */

#ifndef _Included_nativeLib_CMatrix
#define _Included_nativeLib_CMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLib_CMatrix
 * Method:    multiplyMatrix128
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeLib_CMatrix_multiplyMatrix128
  (JNIEnv *, jobject);

/*
 * Class:     nativeLib_CMatrix
 * Method:    multiplyMatrix1024
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeLib_CMatrix_multiplyMatrix1024
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
